services:
  portfolio:
    build: .
    container_name: my-portfolio
    restart: unless-stopped
    ports:
      - "8081:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bimporto-router.rule=Host(`bimporto.my.id`) || Host(`www.bimporto.my.id`)"
      - "traefik.http.routers.bimporto-router.tls=true"
      - "traefik.http.routers.bimporto-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.bimporto-service.loadbalancer.server.port=80"
    networks:
      - coolify

networks:
  coolify:
    external: true